### ISSUE TITLE
Integration edgeos not found when trying to verify its device_tracker platform.

### ISSUE THREAD

**Issue by JunShine** [dels78/home-assistant-device_tracker.edgeos#1]
I just updated to HA0.92, and now I get a error:
Integration edgeos not found when trying to verify its device_tracker platform.

**Comment by iptvcld** [comment]
I am having the same issue..

**Comment by damien67** [comment]
What version have you guys updated from?
0.88 brought changes in the folder structure for custom components.

https://hasspodcast.io/ha044/

Important changes if you’re using custom components
Home Assistant is moving to a new file structure, which may impact custom components which override a built-in Home Assistant platform.
As an example, if you’ve developed a custom component which overrides the built-in Philips Hue component, you’ll need to rename your custom component from light/hue.py to hue/light.py

**Comment by iptvcld** [comment]
So then would it be edgeos/device_tracker.py

**Comment by damien67** [comment]
So I have:
Folder "custom_components", in which I have a folder called "edgeos", in which I have a "device_tracker.py" file.
I am currently on 0.91.1 and had to modify all this moving to 0.88. I have not updated to 0.92 yet.
Please let me know if that works, so that I know I can upgrade safely (will probably wait for 93 at this point).

Hope it helps!

**Comment by iptvcld** [comment]
I am on on .92.2 and i am still getting the below error:
Integration edgeos not found when trying to verify its device_tracker platform.
Folder = custom_components\edgeos
File = device_tracker.py

I get the error in HA when i click on check config

**Comment by JunShine** [comment]
thanks everyone！
I found some information .. here...
https://developers.home-assistant.io/blog/
https://developers.home-assistant.io/docs/en/creating_integration_manifest.html
The 0.92 version look so different。I installed it back to 0.86......

**Comment by iptvcld** [comment]
Is there a fix for this?

**Comment by iptvcld** [comment]
Any updates on this on when this can be fixed?

**Comment by damien67** [comment]
@iptvcld Figured it out. Upgraded yesterday to 0.92 and realized my logs weren't showing the usual "You are using a custom integration for edgeos which has not been tested by Home Assistant....".
You have to add a empty file called __init__.py in the "edgeos" folder (next to device_tracker.py). 
Once I added the file it worked again.

**Comment by iptvcld** [comment]
Thanks for the reply - i have the below in the config and i am still getting the same error in the forum:
- platform: edgeos
  host: 192.168.2.1
  username: username
  password: password
  interval_seconds: 60
  track_new_devices: false

Folder Layout: custom_components\edgeos
Files: device_tracker.py and init.py

Any help would be great!

**Comment by iptvcld** [comment]
NVM.. i rebooted my VM and was able to get it to work. Thanks again!
